### ISSUE TITLE
Choose number of genes from summary page

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#114]
On the summary page, I can only copy all genes to the clipboard. We need to have the select n genes option on this page also.

child of #108

**Comment by adityaekawade** [comment]
The user can also select/ deselect by clicking the checkbox or row and the number of genes to be copied/ exported will be updated. I haven't added the select N genes options because the genes that are unique to GTR or phenolyzer cannot be determined currently which would come first. 
For example, if I select 25 genes, it would first select the common genes and then the GTR genes. But the phenolyzer genes won't be included. I am not sure this would be right. Any suggestions on this?

**Comment by AlistairNWard** [comment]
I think this raises a good point and we can discuss in the IOBIO meeting. We could:

1. Come up with a better way of sorting the summary of genes, and then allow selection of top N genes, or

2. Demand that the user does the selection on the individual sources, and then the summary screen just shows the summary, but you can't do a top N selection
