### ISSUE TITLE
test.user showing in GTR search box

### ISSUE THREAD

**Issue by tonydisera** [iobio/genepanel.iobio#169]
(dev2 build)
<img width="630" alt="screen shot 2018-07-13 at 10 22 06 am" src="https://user-images.githubusercontent.com/8420103/42702407-ab3bf022-8686-11e8-8c64-001ca06a5dce.png">

**Comment by adityaekawade** [comment]
I had also noticed this yesterday when you logged in with the saved password from the extension. This issue seems to be because of Google chrome's autofill property. 

I have changed the attribute from autocomplete = "off" to autocomplete ="false".
Ref: https://stackoverflow.com/a/15917221/2150900
https://stackoverflow.com/a/29582380/2150900

I will let you know when I update the nv-dev-new so you can check it.

**Comment by tonydisera** [comment]
Interesting!  Thanks for info.  I think this bit me too on the gene search panel.

**Comment by AlistairNWard** [comment]
Is this resolved? I don't see it any more.
