### ISSUE TITLE
Card styling

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#191]
I added Tony to this, so she can have a look, since I'm far from an expert on this. I think the cards are looking way better, and are far more usable. I think that we want to refine them to get the positioning of elements, sizes and spacings correct though. Tony, do you have any thoughts?

**Comment by tonydisera** [comment]
Adit,
The styling is looking great!  Here are a few of minor UI refinements I would suggest:
1.  The progress bar under the GTR and Phenolyzer search is still a dark cyan.  Since we don't have a secondary color, I would go with the primary blue color for the search bar.
2. Some labels are black and others are grey.  Is this intentional?
<img width="251" alt="screen shot 2018-07-23 at 8 46 09 am" src="https://user-images.githubusercontent.com/8420103/43083977-f851ef12-8e54-11e8-8252-df4be864a531.png">
<img width="339" alt="screen shot 2018-07-23 at 8 46 14 am" src="https://user-images.githubusercontent.com/8420103/43083985-fc86968c-8e54-11e8-8a4c-aaaa5b52869b.png">

**Comment by AlistairNWard** [comment]
Thanks Tony! As for 9, the bottom border is the selected card, but I agree that it doesn't really belong on the Genes card. It is a summary card that cannot be focused on. If you click 'view and filter' on another card, this border moves to the active card.

One other minor detail to go with this issue. If you mouse over the column titles on the gene list table, the cursor changes to suggest that the titles are clickable. They are not.

**Comment by adityaekawade** [comment]
Thank you Tony, for such a detailed analysis! 

4. I added more spacing there just to make it look less crowded. I agree having consistent spacing across all cards would look better. 
11. New Analysis was added in the navbar because it clears all the results from all the components. Having it in the search panel might make the user feel that it would clear only the results of the specific component.  
12 and 13 are unnecessary and I will take them out. 
15. “Links” would be more appropriate than “More” 
16. We added “View & Filter” to make it clear to the users that these are filtering options.

**Comment by AlistairNWard** [comment]
For 15, we can look to other table examples. Ir seems that people use vertical ellipses rather than horizontal. And often there is no title in the table for that column.

![Screen Shot 2018-07-23 at 2.32.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a37af111294f5f585ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a29941c95df549e24a54a41a3160e4772431.png)
![Screen Shot 2018-07-23 at 2.35.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a37af1112e4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e24a54a41a3161e3702431.png)
![Screen Shot 2018-07-23 at 2.36.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a37af1112d4f5a585ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a29941c95df549e24a54a41a3161e3732431.png)

**Comment by adityaekawade** [comment]
8- I think we can remove that tooltip. It has conditions information and links which is also present in the last column. I think we can add the conditions information in the last column (more)

**Comment by AlistairNWard** [comment]
1. If I click on the vertical ellipsis at the end of a row, the modal pops up. There is a horizontal line separating the Links title to the links. This seems out of place. Could we improve the styling of this modal and make it more attractive?

2. Tony's point 11. It seems odd to have functionality in the top menu bar that is specific to the GTR page. Could we do some research to find a better placement for these buttons?

3. Tony's point 15. We could use links as a title (the title is currently 'Lnks'!), but maybe this column doesn't need a title?

**Comment by adityaekawade** [comment]
2. The "clear all" button in the top menu bar clears results from all the components and not specifically from the GTR. Since it acts on all the components, I felt it was best to add to the top. We can try to move it next to the "Generate Gene List" button but that area may get crowded.

3. No title is better than 'Lnks'!

**Comment by AlistairNWard** [comment]
2. That's a good point - Clear is applicable to the whole app.

**Comment by adityaekawade** [comment]
3. Can we show just the links in the last column when the vertical ellipsis is clicked? So this will be standard in all the components.

**Comment by tonydisera** [comment]
Yes, I think showing the links when the ellipse is clicked makes sense.  But in other apps, we might have more functionality, so we would want to show a menu in those cases.

**Comment by adityaekawade** [comment]
I have styled the links popup modal in the GTR component. Please let me know if that looks good.

**Comment by AlistairNWard** [comment]
I was the one that suggested removing the title. From what I can tell, the vertical ellipsis is used for additional information and functionality, and when used in a table, tends not to have a title. At least that's the case for the things I've looked at. We could easily extend this to include more than links, so I figured no title was fine. Happy to go with a team decision, of course!

**Comment by tonydisera** [comment]
Yeah, that makes sense.  Let's leave the title off.

**Comment by adityaekawade** [comment]
I have kept the title blank for the links column!!
