### ISSUE TITLE
Pasting term returns no data

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#234]
This one is odd:

1. In GTR, paste "Autoimmune thrombocytopenia"

2. Click "Generate gene list"

You get the warning that this returned no data. If you paste this term and click enter, or select the term from the dropdown, everything is fine, but clicking the button fails.

**Comment by adityaekawade** [comment]
Oh! The drop-down item maps the search term with the ConceptId and since we changed the way search works, pasting the term doesn't currently track the ConceptID. Hence no data is returned. 
I will handle this scenario to get the ConceptID when a search term is pasted and clicked "Generate gene list".
