### ISSUE TITLE
Define panel categories

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#235]
If you click the setting wheel, this should probably open a modal where we can set the values. This should be laid out more clearly, so it is obvious what these values are. The user is expecting to see the definition of a "specific panel", a "moderate panel" etc. but just has an upper and lower limit to set which isn't immediately clear what these are. Maybe a modal would give us some room to add an explanation, then have the limits for each of the panel categories, even if some of these values are hard coded, e.g. the lower limit for specific panels is probably always set a 0, and the upper limit for general at infinity.

**Comment by AlistairNWard** [comment]
Yes, I can certainly help with the text. If we put titles in this document (https://docs.google.com/document/d/1ZVcp3TDLHd6ptVSVCXz9zgUfNNvYcUx6b4EUV3TP-t4/edit#) for all the text that needs writing, I can got in and fill them out

**Comment by AlistairNWard** [comment]
I think this modal could be styled a little nicer.

Also, change contains to contain in the definitions.

**Comment by adityaekawade** [comment]
Here is a fancy mockup that I tried. Instead of using an input box to enter values there will be a slider. And there is a range above the slider that corresponds to the values selected. Also, the colors correspond to the panel's definition.

![Group 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46cf86953692c3fbcda5fd53b652fa912a5265296b51a2727581ba71bd177d075f0d4bac41590d46ffa88129f2a42062c80d55b98e30063e937f03a6aa801fb500bf23884783b3ba8f4dc5e13d37aa.png)

**Comment by AlistairNWard** [comment]
I like it. Just playing around with this idea:
![Untitled-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46dd9a8e2a968fac8ba4ee01e81fe086264c22703d46f9692584ba2dbb1b22035a0918ac135d5f44fdab8b28f7be3e24984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b5b58a4ac1ee3d27e48e9d02.png)

**Comment by adityaekawade** [comment]
I have come up with the following design for the edit panel modal. Since the slider needs to have range, I have kept the maximum at 100. This means that Moderate panels can have a maximum of 100 Genes (This number can be changed). The definitions above the slider also act as the legend.
![Screen Shot 2018-08-13 at 3.04.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f06b7191a37bf1122f4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54fe04450ad1a3f67e7762431.png)

 The vuetify component that I have used here (or the standard HTML range slider input) has the option for adding only two colors (One color for the Slider and one color for the track). So it was a bit tricky to come up with this design for the slider. 

I have also extended the portion of the slider beyond the maximum range, but the slider can only slide to the maximum limit. This is because we need to show portion for the General panels. There is also an infinity symbol which indicates that there is no limit for the number of genes in the General panel. If there was no extended portion and if the slider was at the maximum limit it looked like the General Panels did not exist. 
I also tried to make this slider vertical, but it was not sliding smoothly. So I kept it horizontal.
![Screen Shot 2018-08-13 at 3.04.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f06b7191a37bf1122f4f5c5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54fe04453a614326be4702431.png)

There is also a “Show Panels Distribution” button which expands to show how many genes a type of panel can contain. Please have a look at it and let me know you suggestions.

**Comment by AlistairNWard** [comment]
Looks good to me.
