### ISSUE TITLE
Make conditions histogram interactive

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#76]
User should be able to interact with both histograms.

**Comment by adityaekawade** [comment]
This chart is interactive now, but since it is based on the panel's data, using the brush on it would change the data and the chart also gets updated. And to get back to the originial chart, have a clear filter button.  Let me know your opinion on this:
![1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c1281f2277705da17e7683b32aea122b500d5d4dfd495a0b56e0ebcb7af8e2632dd3165eafc3674d75ce3710a9ba861bbb02b324834f8db2aec7.png)
![2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46bad6d6619291a685ecbc57e607b2c1281f2277705da17e7683b32aea122b500d5d4dfd495a0b56e0ebcb7af8e2632dd3165eafc3674d76c63710a9ba861bbb02b3288a4f85b3aec7.png)
![4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46bcd6d6619291a685ecbc57e607b2c1281f2277705da17e7683b32aea122b500d5d4dfd495a0b56e0ebcb7af8e2632dd3165eafc3674d75c13710a9ba861bbb02b3288c468db2aec7.png)

**Comment by AlistairNWard** [comment]
I think we need some time to think about this a little more; but here are some preliminary thoughts:

1.  It is definitely not desirable that having made a selection, I have to open the side panel to clear things. This isn't intuitive and would trip people up.

2. It isn't immediately obvious that the data now being shown in the gene membership chart is just the data filtered from the conditions chart. Here is something I floated for the hub charts that might be worth considering. But we should think it through and make sure you have a plan that you like!

After selecting a data subset, the filtered out data is shown

**Comment by adityaekawade** [comment]
I meant having a "clear selection" button next to the chart so that the user can get back the original chart. Opening the filter panel will be inconvenient. 
I will try to keep the original charts even after selection. The idea that you have suggested also looks good! I will try and look into it.

**Comment by AlistairNWard** [comment]
Yeah, putting a clear button for now would work. But we will have to make sure that it is intuitive.

**Comment by adityaekawade** [comment]
We can delete this
