### ISSUE TITLE
Select top N genes

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#79]
We should standardize across apps how we present this information. For example, in the mockup in issue #56, I put this as a dropdown similar to how Tony has implemented gene selection in the vue version of gene.iobio.

**Comment by adityaekawade** [comment]
Should the select top N genes dropdown be in the filter panel as well or just inside the results component? The mockup shows an input box in the filter panel.

**Comment by AlistairNWard** [comment]
Good point. I would say for now that redundancy doesn't really seem necessary. I think it's important to have that filter in the results component, as this is likely a common use filter and we wouldn't want to force the user to open the filter panel to use. I would then omit it from the filter panel, since that doesn't add anything.

**Comment by adityaekawade** [comment]
![Screen Shot 2018-04-18 at 12.32.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a379ed0c2853415b46bc21254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e54d52a217346be471346e0a.png)

I have added an arrow next to the dropdown because If I enter a number which is not in the dropdown, focussing out of the input does not fire an event. I have to enter again in the input box and focus out to fire that event. This might be a bug in the select component of vuetify. Having the arrow, the user can click it to fire that event. 

The width of the input looks slightly more. If I reduce it, the label "Select Genes" cuts off. Or I can have the label as just "Genes" as it is in the vue version of Gene.iobio.

**Comment by AlistairNWard** [comment]
Looks good to me.

**Comment by adityaekawade** [comment]
Great! I will add this design to both pheonlyzer and GTR.

**Comment by adityaekawade** [comment]
There still seems to be a bug, I have moved this back to in-progress.

**Comment by adityaekawade** [comment]
1. Select a value from the drop-down and click the "Go" button. 
Expected behavior: The number of genes should be updated based on the value selected from Drop down. 
Actual behavior: Worked as expected. 

2. Manually enter a value in the input. Press a tab key or anywhere on the screen and click the "Go" button. 
Expected behavior: The number of genes should be updated based on the value entered. 
Actual behavior: Worked as expected. 

3. Manually enter a value in the input and directly click the "Go" button. 
Expected behavior: The number of genes should be updated based on the value entered. 
Actual behavior: The number would not update on the first click. Debug statement shows the last selected value instead of the newly entered value. Clicking the "Go" button for the 2nd time would update it.

**Comment by adityaekawade** [comment]
This was a crazy bug. I have fixed it.
Please review the issue by checking the above steps.

**Comment by AlistairNWard** [comment]
I actually noticed this myself yesterday, but didn't add it. It was as though the first click was just deselecting the selection box, and then you needed to click again for the value to take effect. I just tried again now, and it does indeed work as expected.
