### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#80]
Material design has recommendations on the dimensions to use for tabs. We should look at following these guidelines

**Comment by adityaekawade** [comment]
The dimensions specified for the height of the tabs is 48dp: https://material.io/guidelines/components/tabs.html#tabs-specs

I checked the vuetify example for tabs, their height is 48:
![Screen Shot 2018-04-23 at 11.55.45 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a379ee0c2e54415b4bbc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f349e54855a3173367e776366e0a.png)

We are at 58 because we had increased the font size and added the notificiation label.
![Screen Shot 2018-04-23 at 12.00.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a379ed0c2b51415d46bc21254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e54855a3163267e277366e0a.png)

Vuetify examples are based on the material design, so I am pretty sure they are acurate. My concern is the unit dp, which is for android devices. But our height is definitely more.

**Comment by AlistairNWard** [comment]
material design has stuff for desktop applications as well, doesn't it? We shouldn't be designing for mobile devices since we are not mobile (yet)!

**Comment by adityaekawade** [comment]
That link has the dimensions for desktop tabs at the bottom which I was talking about. But the unit specified is dp (which is used for mobile devices if I am not wrong).

**Comment by AlistairNWard** [comment]
I don't know about that!

**Comment by adityaekawade** [comment]
I have changed the dimension according to the vuetify. I  have also reduced the font size a little.
![Screen Shot 2018-04-24 at 10.44.55 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f76b7191a379ef0c2f55415a4bbc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e5485dac173364e577366e0a.png)

**Comment by AlistairNWard** [comment]
Looks good to me, and is defendable!
